[package]
name = "edge-detection"
version = "0.0.1"
authors = ["polyfloyd <floyd@polyfloyd.net>"]
license = "MIT"
description = "The canny edge detection algorithm"

include = [
    "src/**/*.rs",
    "Cargo.toml",
]

[dependencies]
image = "~0.17.0"
