[package]
name = "edge-detection"
version = "0.1.1"
authors = ["polyfloyd <floyd@polyfloyd.net>"]
license = "MIT"
repository = "https://github.com/polyfloyd/edge-detection-rs"
description = "The canny edge detection algorithm"
readme = "README.md"
keywords = ["computer-vision", "canny"]
categories = ["algorithms", "multimedia::images", "science", "visualization"]

include = [
    "src/**/*.rs",
    "media/**/*.png",
    "Cargo.toml",
]

[badges]
travis-ci = { repository = "polyfloyd/edge-detection-rs", branch = "master" }

[features]
unstable = []

[dependencies]
image = "~0.17.0"
rayon = "~0.8.2"
